general:
  seed: 42


paths:
  ptb_train: ../data/ptbdb_train.csv
  ptb_test: ../data/ptbdb_test.csv
  logistic_regression_feat_eng: ../weights/logistic_regression_feat_eng.pkl
  logistic_regression_no_feat_eng: ../weights/logistic_regression_no_feat_eng.pkl
  catboost_feat_eng: ../weights/catboost_feat_eng.pkl
  catboost_no_feat_eng: ../weights/catboost_no_feat_eng.pkl
  rf_feat_eng: ../weights/rf_feat_eng.pkl
  rf_no_feat_eng: ../weights/rf_no_feat_eng.pkl


logistic_regression:
  penalty: elasticnet
  solver: saga
  cv: 5
  max_iter: 1000
  Cs: 10
  num_l1_ratios: 10
  use_smote: False

random_forest_no_feat_eng:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: sqrt
  bootstrap: True
  criterion: gini
  use_smote: False

random_forest_feat_eng:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: sqrt
  bootstrap: True
  criterion: gini
  use_smote: False

catboost:
  num_iter: 1000