general:
  seed: 42


paths:
  lightgbm_feat_eng: ../weights/lightgbm_feat_eng.pkl
  lightgbm_no_feat_eng: ../weights/lightgbm_no_feat_eng.pkl
  logistic_regression_feat_eng: ../weights/logistic_regression_feat_eng.pkl
  logistic_regression_no_feat_eng: ../weights/logistic_regression_no_feat_eng.pkl
  ptb_test: ../../data/ptbdb_test.csv
  ptb_train: ../../data/ptbdb_train.csv
  rf_feat_eng: ../weights/rf_feat_eng.pkl
  rf_no_feat_eng: ../weights/rf_no_feat_eng.pkl


logistic_regression:
  Cs: 10
  cv: 5
  max_iter: 1000
  num_l1_ratios: 10
  penalty: elasticnet
  solver: saga

random_forest_no_feat_eng:
  bootstrap: false
  criterion: log_loss
  max_depth: 30
  max_features: sqrt
  min_samples_leaf: 1
  min_samples_split: 2
  n_estimators: 402

random_forest_feat_eng:
  bootstrap: false
  criterion: entropy
  max_depth: 25
  max_features: sqrt
  min_samples_leaf: 1
  min_samples_split: 4
  n_estimators: 998


lightgbm_no_feat_eng:
  learning_rate: 0.09991472256779813
  max_depth: 14
  min_data_in_leaf: 80
  min_gain_to_split: 0.002058283006754594
  n_estimators: 308
  num_leaves: 184

lightgbm_feat_eng:
  learning_rate: 0.062170719319985725
  max_depth: 5
  min_data_in_leaf: 15
  min_gain_to_split: 0.002071608294861996
  n_estimators: 868
  num_leaves: 91




