general:
  seed: 42
  
paths:
  ptb_train: ../../data/ptbdb_train.csv
  ptb_test: ../../data/ptbdb_test.csv
  transformer_model: ../weights/transformer_model.pth
  summary_writer: logs/transformer

preprocessing:
  validation_size: 0.2

dataloader:
  train_batch_size: 32
  val_batch_size: 256
  test_batch_size: 256

adamw:
  weight_decay: 0.0001 
  learning_rate: 0.0003

scheduler:
  factor: 0.5
  patience: 5

transformer:
  num_epochs: 100
  num_classes: 2
  input_size: 1
  model_size: 64
  num_heads: 8
  num_encoder_layers: 5
  dim_feed_forward: 128
  dropout: 0.0
  transformer_activation: gelu
  use_padding_mask: False

early_stopping:
  start: 20
  patience: 10
